### PR TITLE
Add runme

### PR DESCRIPTION
**Pull request by degrammer**
Adding [runme](https://runme.dev/), a CLI that allows discover and run code snippets directly from your README.md or other markdowns

### CODE REVIEW

**Comment by rothgar** [comment]
I’m not sure I understand how this is a terminal user interface (TUI) are there screenshots or TUI options?

**Comment by degrammer** [comment]
> I’m not sure I understand how this is a terminal user interface (TUI) are there screenshots or TUI options?

@rothgar yeah, there is a CLI for runme too, you can install it via 
`brew install stateful/tap/runme`

terminal

**Comment by degrammer** [comment]
@rothgar  More screenshots for the terminal, read more at [https://runme.dev/docs/cli](https://runme.dev/docs/cli)
runme

**Comment by rothgar** [comment]
Cool, thanks for clarifying.

**Pull request merged**
