### PR TITLE
added cheatshh in dashboard

### PR DESCRIPTION
**Pull request by AnirudhG07**
Cheatshh is a fzf powered command line tool where you can add commands so that you don't have to remember them.

It is a cool TUI and it should be added to this awesome list.
Feel free to change it's position according to your liking.

### CODE REVIEW

**Comment by rothgar** [comment]
Thank you for the PR.

I've avoided adding wrappers to this list (e.g. scripts that execute `fzf`) because there's a lot of them and most of the ones I've seen don't provide new functionality on top if a selection menu.

Maybe I misunderstood what this command does. If so please let me know.

**Comment by AnirudhG07** [comment]
Cheatshh uses fzf for its preview and search options, while all the other function mainly are done using bash scripting with whiptail and json files, this includes adding a command, grouping them, deleting commands/groups, bookmarking commands, etc. All these cannot be done using `fzf` features but done through above mentioned scripts.

The preview showed in the github, does not show all these features thus it may only look like a selection menu, hence i can understand by what you meant. I believe it should be added, since many cheatsheet based tools i have seen don't use fzf but then dont have various functionalities cheatshh provides.

Let me know if you would like to anything more. :)

**Comment by rothgar** [comment]
I'm still a bit hesitant to put wrappers in the list because there are too many that exist and it could quickly overload the list with unique use cases using similar tools.

I'll include this one and we'll see if it becomes a problem.

Can you please update the PR to put cheatshh into alphabetical order in the list sub group?

**Comment by AnirudhG07** [comment]
@rothgar I have updated the PR and added it to correct position. Thanks!

**Pull request merged**
