### PR TITLE
Add ATAC, the modern TUI API Client

### PR DESCRIPTION
**Pull request by Julien-cpsn**
ATAC is Arguably a Terminal API Client. Feature-full, free, open-source, offline and account-less.

### CODE REVIEW

**Comment by ccoVeille** [comment]
For lazy people who may come after me.

Here is the repository link without having to open the diff and copy paste it

https://github.com/Julien-cpsn/ATAC

**Comment by Julien-cpsn** [comment]
@ccoVeille haha thanks! I forgot about this 👀

**Comment by ccoVeille** [comment]
Great tool idea BTW. I cannot bare with heavy client that became postman, then insomnia.

I'm still not convinced by bruno as it is full of bug

**Comment by Julien-cpsn** [comment]
@ccoVeille Thank you, feedback is welcome!
Yes, they are all very slow and has killer red flags for me... like must have an account and an online connection for Postman and Insomnia. The worst is that you do not even own your data, its all on their servers.

**Comment by rothgar** [comment]
This looks really neat. Could you please move it into alphabetical order in the section.

**Comment by Julien-cpsn** [comment]
@rothgar done! thanks man!

**Pull request merged**
