### PR TITLE
Add Thermage Library

### PR DESCRIPTION
**Pull request by Awilum**
Thermage is a PHP library that provides a fluent and incredibly powerful, object-oriented interface for customizing CLI output text color, background, formatting, theming and more.

### CODE REVIEW

**Comment by rothgar** [comment]
I might be wrong but this looks like a text output formatter and not a user interface library. I've been drawing a line between formatters and dynamic interfaces (eg will resize with terminal size) or allows for interaction.

Let me know if I'm mistaken on the abilities of this library.

**Comment by Awilum** [comment]
Hello @rothgar 

Thermage it's not just a text output formatter. Thermage has built-in components, called Elements, which can be used individually or together to generate pretty console output.

For e.g. 
Chart  - https://awilum.github.io/thermage/documentation/elements/chart/
Canvas - https://awilum.github.io/thermage/documentation/elements/canvas/
Cowsay - https://awilum.github.io/blog/using-cowsay-element-in-thermage/
Alert - https://awilum.github.io/thermage/documentation/elements/alert/
Div - https://awilum.github.io/thermage/documentation/elements/div/
and etc...

more terminal ui components are coming....

**Comment by rothgar** [comment]
Thanks for clarification. Would you mind putting the library in alphabetical order in the list?

**Comment by Awilum** [comment]
> Thanks for clarification. Would you mind putting the library in alphabetical order in the list?

https://github.com/rothgar/awesome-tuis/pull/93

**Pull request closed without merging**
